MAX, MIN, ROUND, LENGTH, ABS = 'MAX', 'MIN', 'ROUND', 'LENGTH', 'ABS'

#basic token
INT, REAL, SYMBOL, CONST = 'Int', 'Real', 'Symbol', 'const'
PLUS, MINUS, MUL, DIV = 'PLUS', 'MINUS', 'MUL', 'DIV'
LPAREN, RPAREN = 'LPAREN', 'RPAREN'
NIL, TRUE, FALSE, EQUAL = 'NIL', 'TRUE', 'FALSE', 'EQUAL'
ID, VAR, QUOTE, LIST, COLON = 'ID', 'Var', 'QUOTE', 'LIST', 'COLON'
SQUARE_LPAREN, SQUARE_RPAREN = 'SQUARE_LPAREN','SQUARE_RPAREN'
IMUL, IDIV, IPLUS, IMIN, ISEQUAL = 'IMUL', 'IDIV', 'IPLUS', 'IMIN', 'ISEQUAL'
DEFUN,POW,ROUND, FUNCTION,PRINT = 'DEFUN' ,'POW','ROUND', 'FUNCTION', 'PRINT'
DOUBLE_QUOTE,SENTENCE = "DOUBLE_QUOTE", 'SENTENCE'
QUOTE = "QUOTE"
ISNULL = "ISNULL"
INPUT = "INPUT"
MAP = "MAP"
APPLY = 'APPLY'
SET = 'SET!'
KEEP_MATCHING_ITEMS = 'KEEP_MATCHING_ITEMS'
DELETE_MATCHING_ITEMS = 'DELETE_MATCHING_ITEMS'
#program_kill_function
ABORT, SPACE = 'ABORT', 'SPACE'
함수정의, 만약, 정수, 실수, 정의, 배열, 변수 = '함수정의', '만약', '정수', '실수', '정의', '배열', '변수'

GREAT, LESS, GREAT_EQUAL, LESS_EQUAL = 'GREAT', 'LESS', 'GREAT_EQUAL', 'GREAT_EQUAL'
#builtin function
DEFINE, IF, LAMBDA, CONS, TYPE, CAR, CDR, ADD, LET = 'DEFINE', 'IF', 'LAMBDA', 'CONS', \
'TYPE', 'CAR', 'CDR', 'ADD', 'LET'
DEFUN_MODULE = "DEFUN_MODULE"
SHARP_PY = "SHARP_PY"
SQRT = "SQRT"
CAAR, CADR, CDAR, CDDR, SWAP = 'CAAR', 'CADR', 'CDAR', 'CDDR', 'SWAP'
SIZE = 'SIZE'
LET = 'LET'
EOF = 'EOF'
ISINTEGER = 'ISINTEGER'
ISREAL = 'ISREAL'
ISNUM = 'ISNUM'
ISSYMBOL = 'ISSYMBOL'
ISNULL = 'ISNULL'
ISLIST = 'ISLIST'
ISSENTENCE = 'ISSENTENCE'
ISZERO = 'ISZERO'
ISPOSITIVE = 'ISPOSITIVE'
ISNEGATIVE = 'ISNEGATIVE'
SORT = "SORT"
SETCAR="SETCAR"
SETCDR="SETCDR"

#file i/o and bufferd i/o
DISPLAY, INPUT = 'DISPLAY', 'INPUT'

#report
REPORT = 'REPORT'

#program entry point
MAIN = 'MAIN'#(MAIN -- -- -- -- )

#set a environment
DEBUG = 'DEBUG'

#global stack area
global_envs = []
#boolean value ###BUG EXISTS
DEBUG_CODE_OK = ''
#set file number
FILE_NUM = 1